farmWorld: farms
prices:
  LONG_GRASS: 0.5
  CROPS: 1
  CARROT: 3
  POTATO: 6
  BEETROOT_BLOCK: 20
  MELON_BLOCK: 50
  PUMPKIN: 100
  CACTUS: 250
  SUGAR_CANE_BLOCK: 1000
levels:
  LONG_GRASS: 1
  CROPS: 1
  CARROT: 2
  POTATO: 3
  BEETROOT_BLOCK: 4
  MELON_BLOCK: 5
  PUMPKIN: 6
  CACTUS: 7
  SUGAR_CANE_BLOCK: 8